apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-kubernetes-deployment-deployment
  labels:
    app: springbootazure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootazure
  template:
    metadata:
      labels:
        app: springbootazure
    spec:
      containers:
        - name: springbootazure
          image: hemantapcontainerregistry.azurecr.io/spring-boot-kubernetes:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: springbootazure-service
spec:
  selector:
    app: springbootazure
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer